version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./psql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"